---
description: "Show what changed under a document's covers: paths, then record that you have read it: ilk record review <file>"
# Generated by ilk. Do not edit — run `ilk apply` to regenerate, or edit the layer that produced it.
---

Run this and report what it printed:

```
ilk record review $ARGUMENTS
```
