---
description: "Create a record document with correct naming and frontmatter: ilk record new <docs|plans|log> <title>"
# Generated by ilk. Do not edit — run `ilk apply` to regenerate, or edit the layer that produced it.
---

Run this and report what it printed:

```
ilk record new $ARGUMENTS
```
