---
description: "List or search summaries: ilk session-summaries list [--query TEXT] [--limit N]"
# Generated by ilk. Do not edit — run `ilk apply` to regenerate, or edit the layer that produced it.
---

Run this and report what it printed:

```
ilk session-summaries list $ARGUMENTS
```
