---
name: write-decision
description: Record an architectural or process decision so future sessions inherit it. Use when a choice is made that a later reader would otherwise have to reverse-engineer, or would plausibly undo by accident.
# Generated by ilk. Do not edit — run `ilk apply` to regenerate, or edit the layer that produced it.
ilk_layer: ilk/record
---

# Write a decision

Record a choice so that a future session inherits it instead of relitigating it.

## When this is worth doing

Write a decision when **a later reader would otherwise have to reverse-engineer the
reasoning, or would plausibly undo the choice by accident.** That is the whole test.

Worth recording: picking Postgres over DynamoDB; deciding retries live in the client
not the gateway; agreeing that a module stays synchronous despite the obvious
temptation; choosing not to do something, and why.

Not worth recording: naming a variable; anything the code states plainly on its own;
a choice with no alternatives worth mentioning.

## How

Create the document:

```
ilk record new docs "Retries live in the client"
```

Rename the generated file so its type prefix is `DEC`, e.g. `DEC-client-retries.md`.

Then fill in these sections. Keep it short — a decision document that runs to three
pages will not be read, which defeats the purpose.

```markdown
## Context

What was true that forced a choice. The constraints, not the narrative.

## Decision

One paragraph, present tense, active voice. "Retries live in the client."

## Alternatives considered

Each with the reason it lost. This is the section that stops the decision being
re-opened six weeks from now — without it, the next reader only sees the winner and
assumes the alternatives were never examined.

## Consequences

What this makes easy, and what it makes hard. Be honest about the second one; a
decision doc that lists only benefits reads as advocacy and gets discounted.

## Revisit when

The condition that would make this decision wrong. If you cannot name one, say so
explicitly — "no foreseeable trigger" is a legitimate answer and is more useful than
silence.
```

## After writing

- Link it from any plan in `plans/` whose work it constrains. `ilk check` verifies
  those links resolve.
- If the decision changes what is *true* right now, also update the relevant
  `ARCH-*.md`. The decision explains why; the architecture doc states what is.
- If it supersedes an earlier decision, set the old document's `status: superseded`
  and link forward to the new one. Do not delete it — the reasoning for the old
  choice is what makes the new one legible.
