---
description: "Read a summary and its publication status: ilk session-summaries read HARNESS SESSION"
# Generated by ilk. Do not edit — run `ilk apply` to regenerate, or edit the layer that produced it.
---

Run this and report what it printed:

```
ilk session-summaries read $ARGUMENTS
```
